In [4]:
# importando bibliotecas necesarias incluyendo los módulos de aprendizaje automático 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [5]:
# cargando el conjunto de datos
prediccion_diabetes = pd.read_excel('Predecir_la_diabetes.xlsx')
prediccion_diabetes

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                    2288.000   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [6]:
X = prediccion_diabetes.loc[:,['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'Age']]
Y = prediccion_diabetes.loc[:,['Outcome']]

In [9]:
X_entr, X_prue, Y_entr, Y_prue = train_test_split(X, Y, test_size=0.3, random_state=0)

In [ ]:
X_entr

In [ ]:
Y_entr

In [10]:
# Escalado de variables
from sklearn.preprocessing import StandardScaler
standard_x = StandardScaler()
X_entr = standard_x.fit_transform(X_entr)
X_prue = standard_x.fit_transform(X_prue)

In [11]:
X_entr

array([[-1.13311543,  0.9144385 ,  1.04559346, ..., -0.71652335,
         1.22646853, -1.05654479],
       [-0.8391623 , -1.19655127, -0.08570438, ..., -0.71652335,
        -1.75097771, -0.55622332],
       [-0.54520916,  0.01416345,  0.01714088, ..., -0.71652335,
         0.56619802, -0.55622332],
       ...,
       [ 0.0426971 , -0.85506763, -0.23997227, ..., -0.71652335,
        -0.941212  , -1.05654479],
       [ 2.10036903, -1.13446334,  0.22283139, ..., -0.71652335,
        -0.26848356,  0.11087198],
       [ 0.33665024,  0.44877899,  0.63421243, ..., -0.71652335,
        -4.01832171,  2.94602702]])

In [26]:
# entrenando el modelo de regresión logística


In [12]:
# ajuste del modelo
reg = LogisticRegression(random_state = 0)
reg.fit(X_entr, Y_entr)

#Predicción
pred = reg.predict(X_prue)

D:\ProgramasInstalados\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [31]:
pred, Y_prue

(array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
        1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0], dtype=int64),
      Outcome
 608        0
 626        0
 678        1
 186        1
 520        0
 ..       ...
 8          1
 529        0
 273        0
 11         1
 677        0
 
 [231 rows x 1 columns])

In [13]:
# EVALUACIÓN
# usando la matriz de confusión para comparar los datos  predecidos y los datos de testeo
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(Y_prue, pred)
conf_mat

array([[133,  24],
       [ 33,  41]], dtype=int64)

In [15]:
133/len(Y_prue)

0.5757575757575758